spring:
  jpa:
    hibernate.ddl-auto: "update"
    open-in-view: false

server:
  error.include-stacktrace: "never"

springdoc:
  api-docs.enabled: true
  swagger-ui.path: "/"

logging.level:
  org.hibernate.SQL: "DEBUG"

ferramong:
  auth:
    base-url: "https://ferramong-auth.herokuapp.com"
    timeout: 120
  pay:
    base-url: "https://ferramong-pay.herokuapp.com"
    timeout: 120
