spring:
  datasource:
    url: "jdbc:h2:mem:testdb"
    username: "sa"
    password: ""
    platform: "h2"
  jpa:
    hibernate.ddl-auto: "update"
    open-in-view: false
  h2:
    console.enabled: true

server:
  port: 8080
  error:
    include-stacktrace: "never"

springdoc:
  api-docs.enabled: true
  swagger-ui.path: "/"

logging.level:
  org.hibernate.SQL: "DEBUG"
  org.hibernate.type.descriptor.sql.BasicBinder: "TRACE"

ferramong:
  auth:
    base-url: "https://ferramong-auth.herokuapp.com"
    timeout: 120
  pay:
    base-url: "https://ferramong-pay.herokuapp.com"
    timeout: 120
